baseURL = 'https://MidhunKumar05.github.io/'
languageCode = 'en-us'
title = 'Midhun Kumar'
theme = 'hugo-noir'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Midhun Kumar"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 2
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 3

[params]
  name = "Midhun Kumar"
  # location = "Your Location"
  description = "Welcome to my portfolio"
  # profile_image = "/images/your-profile.jpg"
  github = "https://github.com/MidhunKumar05"
  linkedin = "https://linkedin.com/in/" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'